name: oura
environment:
  sdk: '^3.5.0'
version: 1.0.3
description: Swagger API client
repository: https://github.com/ArcaneArts/oura
dependencies:
  chopper: ^8.0.1+1
  collection: ">=1.18.0 <2.0.0"
  http: ">=1.1.1 <1.3.0"
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.12
  chopper_generator: ^8.0.1
  json_serializable: ^6.8.0
  swagger_dart_code_generator: ^3.0.0
scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs